version: '3.7'
services:
  db_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nodets
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5435:5432'
